/**
 * FIFA World Cup 2026 — Annex C: allocation of the eight best third-placed
 * teams to Round-of-32 matches.
 *
 * Source (primary): FIFA "Regulations for the FIFA World Cup 26", May 2026
 * edition, Annex C (pp. 80-97):
 * https://digitalhub.fifa.com/m/636f5c9c6f29771f/original/FWC2026_regulations_EN.pdf
 * Cross-checked against the per-slot candidate-group lists in
 * https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage
 * (all 495 x 8 assignments respect the published candidate sets).
 *
 * Extracted programmatically from the official PDF (pypdf text extraction,
 * regex row parse: 495/495 rows, zero conflicts) and validated:
 *  - every row assigns 8 distinct groups,
 *  - the 495 keys cover every C(12,8) combination exactly once,
 *  - every assignment respects the allowed-group constraints of its slot.
 *
 * Key:   the 8 group letters of the qualified third-placed teams, sorted
 *        ascending (e.g. 'EFGHIJKL').
 * Value: 8 group letters - which third-placed team is allocated to the
 *        R32 match hosted by each group winner, in THIRD_SLOT_HOSTS order
 *        [1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L]
 *        (matches M79, M85, M81, M74, M82, M77, M87, M80 respectively).
 * The "// option N" comment is the row number in FIFA's Annex C table.
 */
import type { GroupId } from './types';

/** Group winners that host a third-placed team in the R32, in Annex C column order. */
export const THIRD_SLOT_HOSTS: readonly GroupId[] = [
  'A', 'B', 'D', 'E', 'G', 'I', 'K', 'L',
] as const;

export const R32_ANNEX: Readonly<Record<string, string>> = {
  EFGHIJKL: 'EJIFHGLK', // option 1
  DFGHIJKL: 'HGIDJFLK', // option 2
  DEGHIJKL: 'EJIDHGLK', // option 3
  DEFHIJKL: 'EJIDHFLK', // option 4
  DEFGIJKL: 'EGIDJFLK', // option 5
  DEFGHJKL: 'EGJDHFLK', // option 6
  DEFGHIKL: 'EGIDHFLK', // option 7
  DEFGHIJL: 'EGJDHFLI', // option 8
  DEFGHIJK: 'EGJDHFIK', // option 9
  CFGHIJKL: 'HGICJFLK', // option 10
  CEGHIJKL: 'EJICHGLK', // option 11
  CEFHIJKL: 'EJICHFLK', // option 12
  CEFGIJKL: 'EGICJFLK', // option 13
  CEFGHJKL: 'EGJCHFLK', // option 14
  CEFGHIKL: 'EGICHFLK', // option 15
  CEFGHIJL: 'EGJCHFLI', // option 16
  CEFGHIJK: 'EGJCHFIK', // option 17
  CDGHIJKL: 'HGICJDLK', // option 18
  CDFHIJKL: 'CJIDHFLK', // option 19
  CDFGIJKL: 'CGIDJFLK', // option 20
  CDFGHJKL: 'CGJDHFLK', // option 21
  CDFGHIKL: 'CGIDHFLK', // option 22
  CDFGHIJL: 'CGJDHFLI', // option 23
  CDFGHIJK: 'CGJDHFIK', // option 24
  CDEHIJKL: 'EJICHDLK', // option 25
  CDEGIJKL: 'EGICJDLK', // option 26
  CDEGHJKL: 'EGJCHDLK', // option 27
  CDEGHIKL: 'EGICHDLK', // option 28
  CDEGHIJL: 'EGJCHDLI', // option 29
  CDEGHIJK: 'EGJCHDIK', // option 30
  CDEFIJKL: 'CJEDIFLK', // option 31
  CDEFHJKL: 'CJEDHFLK', // option 32
  CDEFHIKL: 'CEIDHFLK', // option 33
  CDEFHIJL: 'CJEDHFLI', // option 34
  CDEFHIJK: 'CJEDHFIK', // option 35
  CDEFGJKL: 'CGEDJFLK', // option 36
  CDEFGIKL: 'CGEDIFLK', // option 37
  CDEFGIJL: 'CGEDJFLI', // option 38
  CDEFGIJK: 'CGEDJFIK', // option 39
  CDEFGHKL: 'CGEDHFLK', // option 40
  CDEFGHJL: 'CGJDHFLE', // option 41
  CDEFGHJK: 'CGJDHFEK', // option 42
  CDEFGHIL: 'CGEDHFLI', // option 43
  CDEFGHIK: 'CGEDHFIK', // option 44
  CDEFGHIJ: 'CGJDHFEI', // option 45
  BFGHIJKL: 'HJBFIGLK', // option 46
  BEGHIJKL: 'EJIBHGLK', // option 47
  BEFHIJKL: 'EJBFIHLK', // option 48
  BEFGIJKL: 'EJBFIGLK', // option 49
  BEFGHJKL: 'EJBFHGLK', // option 50
  BEFGHIKL: 'EGBFIHLK', // option 51
  BEFGHIJL: 'EJBFHGLI', // option 52
  BEFGHIJK: 'EJBFHGIK', // option 53
  BDGHIJKL: 'HJBDIGLK', // option 54
  BDFHIJKL: 'HJBDIFLK', // option 55
  BDFGIJKL: 'IGBDJFLK', // option 56
  BDFGHJKL: 'HGBDJFLK', // option 57
  BDFGHIKL: 'HGBDIFLK', // option 58
  BDFGHIJL: 'HGBDJFLI', // option 59
  BDFGHIJK: 'HGBDJFIK', // option 60
  BDEHIJKL: 'EJBDIHLK', // option 61
  BDEGIJKL: 'EJBDIGLK', // option 62
  BDEGHJKL: 'EJBDHGLK', // option 63
  BDEGHIKL: 'EGBDIHLK', // option 64
  BDEGHIJL: 'EJBDHGLI', // option 65
  BDEGHIJK: 'EJBDHGIK', // option 66
  BDEFIJKL: 'EJBDIFLK', // option 67
  BDEFHJKL: 'EJBDHFLK', // option 68
  BDEFHIKL: 'EIBDHFLK', // option 69
  BDEFHIJL: 'EJBDHFLI', // option 70
  BDEFHIJK: 'EJBDHFIK', // option 71
  BDEFGJKL: 'EGBDJFLK', // option 72
  BDEFGIKL: 'EGBDIFLK', // option 73
  BDEFGIJL: 'EGBDJFLI', // option 74
  BDEFGIJK: 'EGBDJFIK', // option 75
  BDEFGHKL: 'EGBDHFLK', // option 76
  BDEFGHJL: 'HGBDJFLE', // option 77
  BDEFGHJK: 'HGBDJFEK', // option 78
  BDEFGHIL: 'EGBDHFLI', // option 79
  BDEFGHIK: 'EGBDHFIK', // option 80
  BDEFGHIJ: 'HGBDJFEI', // option 81
  BCGHIJKL: 'HJBCIGLK', // option 82
  BCFHIJKL: 'HJBCIFLK', // option 83
  BCFGIJKL: 'IGBCJFLK', // option 84
  BCFGHJKL: 'HGBCJFLK', // option 85
  BCFGHIKL: 'HGBCIFLK', // option 86
  BCFGHIJL: 'HGBCJFLI', // option 87
  BCFGHIJK: 'HGBCJFIK', // option 88
  BCEHIJKL: 'EJBCIHLK', // option 89
  BCEGIJKL: 'EJBCIGLK', // option 90
  BCEGHJKL: 'EJBCHGLK', // option 91
  BCEGHIKL: 'EGBCIHLK', // option 92
  BCEGHIJL: 'EJBCHGLI', // option 93
  BCEGHIJK: 'EJBCHGIK', // option 94
  BCEFIJKL: 'EJBCIFLK', // option 95
  BCEFHJKL: 'EJBCHFLK', // option 96
  BCEFHIKL: 'EIBCHFLK', // option 97
  BCEFHIJL: 'EJBCHFLI', // option 98
  BCEFHIJK: 'EJBCHFIK', // option 99
  BCEFGJKL: 'EGBCJFLK', // option 100
  BCEFGIKL: 'EGBCIFLK', // option 101
  BCEFGIJL: 'EGBCJFLI', // option 102
  BCEFGIJK: 'EGBCJFIK', // option 103
  BCEFGHKL: 'EGBCHFLK', // option 104
  BCEFGHJL: 'HGBCJFLE', // option 105
  BCEFGHJK: 'HGBCJFEK', // option 106
  BCEFGHIL: 'EGBCHFLI', // option 107
  BCEFGHIK: 'EGBCHFIK', // option 108
  BCEFGHIJ: 'HGBCJFEI', // option 109
  BCDHIJKL: 'HJBCIDLK', // option 110
  BCDGIJKL: 'IGBCJDLK', // option 111
  BCDGHJKL: 'HGBCJDLK', // option 112
  BCDGHIKL: 'HGBCIDLK', // option 113
  BCDGHIJL: 'HGBCJDLI', // option 114
  BCDGHIJK: 'HGBCJDIK', // option 115
  BCDFIJKL: 'CJBDIFLK', // option 116
  BCDFHJKL: 'CJBDHFLK', // option 117
  BCDFHIKL: 'CIBDHFLK', // option 118
  BCDFHIJL: 'CJBDHFLI', // option 119
  BCDFHIJK: 'CJBDHFIK', // option 120
  BCDFGJKL: 'CGBDJFLK', // option 121
  BCDFGIKL: 'CGBDIFLK', // option 122
  BCDFGIJL: 'CGBDJFLI', // option 123
  BCDFGIJK: 'CGBDJFIK', // option 124
  BCDFGHKL: 'CGBDHFLK', // option 125
  BCDFGHJL: 'CGBDHFLJ', // option 126
  BCDFGHJK: 'HGBCJFDK', // option 127
  BCDFGHIL: 'CGBDHFLI', // option 128
  BCDFGHIK: 'CGBDHFIK', // option 129
  BCDFGHIJ: 'HGBCJFDI', // option 130
  BCDEIJKL: 'EJBCIDLK', // option 131
  BCDEHJKL: 'EJBCHDLK', // option 132
  BCDEHIKL: 'EIBCHDLK', // option 133
  BCDEHIJL: 'EJBCHDLI', // option 134
  BCDEHIJK: 'EJBCHDIK', // option 135
  BCDEGJKL: 'EGBCJDLK', // option 136
  BCDEGIKL: 'EGBCIDLK', // option 137
  BCDEGIJL: 'EGBCJDLI', // option 138
  BCDEGIJK: 'EGBCJDIK', // option 139
  BCDEGHKL: 'EGBCHDLK', // option 140
  BCDEGHJL: 'HGBCJDLE', // option 141
  BCDEGHJK: 'HGBCJDEK', // option 142
  BCDEGHIL: 'EGBCHDLI', // option 143
  BCDEGHIK: 'EGBCHDIK', // option 144
  BCDEGHIJ: 'HGBCJDEI', // option 145
  BCDEFJKL: 'CJBDEFLK', // option 146
  BCDEFIKL: 'CEBDIFLK', // option 147
  BCDEFIJL: 'CJBDEFLI', // option 148
  BCDEFIJK: 'CJBDEFIK', // option 149
  BCDEFHKL: 'CEBDHFLK', // option 150
  BCDEFHJL: 'CJBDHFLE', // option 151
  BCDEFHJK: 'CJBDHFEK', // option 152
  BCDEFHIL: 'CEBDHFLI', // option 153
  BCDEFHIK: 'CEBDHFIK', // option 154
  BCDEFHIJ: 'CJBDHFEI', // option 155
  BCDEFGKL: 'CGBDEFLK', // option 156
  BCDEFGJL: 'CGBDJFLE', // option 157
  BCDEFGJK: 'CGBDJFEK', // option 158
  BCDEFGIL: 'CGBDEFLI', // option 159
  BCDEFGIK: 'CGBDEFIK', // option 160
  BCDEFGIJ: 'CGBDJFEI', // option 161
  BCDEFGHL: 'CGBDHFLE', // option 162
  BCDEFGHK: 'CGBDHFEK', // option 163
  BCDEFGHJ: 'HGBCJFDE', // option 164
  BCDEFGHI: 'CGBDHFEI', // option 165
  AFGHIJKL: 'HJIFAGLK', // option 166
  AEGHIJKL: 'EJIAHGLK', // option 167
  AEFHIJKL: 'EJIFAHLK', // option 168
  AEFGIJKL: 'EJIFAGLK', // option 169
  AEFGHJKL: 'EGJFAHLK', // option 170
  AEFGHIKL: 'EGIFAHLK', // option 171
  AEFGHIJL: 'EGJFAHLI', // option 172
  AEFGHIJK: 'EGJFAHIK', // option 173
  ADGHIJKL: 'HJIDAGLK', // option 174
  ADFHIJKL: 'HJIDAFLK', // option 175
  ADFGIJKL: 'IGJDAFLK', // option 176
  ADFGHJKL: 'HGJDAFLK', // option 177
  ADFGHIKL: 'HGIDAFLK', // option 178
  ADFGHIJL: 'HGJDAFLI', // option 179
  ADFGHIJK: 'HGJDAFIK', // option 180
  ADEHIJKL: 'EJIDAHLK', // option 181
  ADEGIJKL: 'EJIDAGLK', // option 182
  ADEGHJKL: 'EGJDAHLK', // option 183
  ADEGHIKL: 'EGIDAHLK', // option 184
  ADEGHIJL: 'EGJDAHLI', // option 185
  ADEGHIJK: 'EGJDAHIK', // option 186
  ADEFIJKL: 'EJIDAFLK', // option 187
  ADEFHJKL: 'HJEDAFLK', // option 188
  ADEFHIKL: 'HEIDAFLK', // option 189
  ADEFHIJL: 'HJEDAFLI', // option 190
  ADEFHIJK: 'HJEDAFIK', // option 191
  ADEFGJKL: 'EGJDAFLK', // option 192
  ADEFGIKL: 'EGIDAFLK', // option 193
  ADEFGIJL: 'EGJDAFLI', // option 194
  ADEFGIJK: 'EGJDAFIK', // option 195
  ADEFGHKL: 'HGEDAFLK', // option 196
  ADEFGHJL: 'HGJDAFLE', // option 197
  ADEFGHJK: 'HGJDAFEK', // option 198
  ADEFGHIL: 'HGEDAFLI', // option 199
  ADEFGHIK: 'HGEDAFIK', // option 200
  ADEFGHIJ: 'HGJDAFEI', // option 201
  ACGHIJKL: 'HJICAGLK', // option 202
  ACFHIJKL: 'HJICAFLK', // option 203
  ACFGIJKL: 'IGJCAFLK', // option 204
  ACFGHJKL: 'HGJCAFLK', // option 205
  ACFGHIKL: 'HGICAFLK', // option 206
  ACFGHIJL: 'HGJCAFLI', // option 207
  ACFGHIJK: 'HGJCAFIK', // option 208
  ACEHIJKL: 'EJICAHLK', // option 209
  ACEGIJKL: 'EJICAGLK', // option 210
  ACEGHJKL: 'EGJCAHLK', // option 211
  ACEGHIKL: 'EGICAHLK', // option 212
  ACEGHIJL: 'EGJCAHLI', // option 213
  ACEGHIJK: 'EGJCAHIK', // option 214
  ACEFIJKL: 'EJICAFLK', // option 215
  ACEFHJKL: 'HJECAFLK', // option 216
  ACEFHIKL: 'HEICAFLK', // option 217
  ACEFHIJL: 'HJECAFLI', // option 218
  ACEFHIJK: 'HJECAFIK', // option 219
  ACEFGJKL: 'EGJCAFLK', // option 220
  ACEFGIKL: 'EGICAFLK', // option 221
  ACEFGIJL: 'EGJCAFLI', // option 222
  ACEFGIJK: 'EGJCAFIK', // option 223
  ACEFGHKL: 'HGECAFLK', // option 224
  ACEFGHJL: 'HGJCAFLE', // option 225
  ACEFGHJK: 'HGJCAFEK', // option 226
  ACEFGHIL: 'HGECAFLI', // option 227
  ACEFGHIK: 'HGECAFIK', // option 228
  ACEFGHIJ: 'HGJCAFEI', // option 229
  ACDHIJKL: 'HJICADLK', // option 230
  ACDGIJKL: 'IGJCADLK', // option 231
  ACDGHJKL: 'HGJCADLK', // option 232
  ACDGHIKL: 'HGICADLK', // option 233
  ACDGHIJL: 'HGJCADLI', // option 234
  ACDGHIJK: 'HGJCADIK', // option 235
  ACDFIJKL: 'CJIDAFLK', // option 236
  ACDFHJKL: 'HJFCADLK', // option 237
  ACDFHIKL: 'HFICADLK', // option 238
  ACDFHIJL: 'HJFCADLI', // option 239
  ACDFHIJK: 'HJFCADIK', // option 240
  ACDFGJKL: 'CGJDAFLK', // option 241
  ACDFGIKL: 'CGIDAFLK', // option 242
  ACDFGIJL: 'CGJDAFLI', // option 243
  ACDFGIJK: 'CGJDAFIK', // option 244
  ACDFGHKL: 'HGFCADLK', // option 245
  ACDFGHJL: 'CGJDAFLH', // option 246
  ACDFGHJK: 'HGJCAFDK', // option 247
  ACDFGHIL: 'HGFCADLI', // option 248
  ACDFGHIK: 'HGFCADIK', // option 249
  ACDFGHIJ: 'HGJCAFDI', // option 250
  ACDEIJKL: 'EJICADLK', // option 251
  ACDEHJKL: 'HJECADLK', // option 252
  ACDEHIKL: 'HEICADLK', // option 253
  ACDEHIJL: 'HJECADLI', // option 254
  ACDEHIJK: 'HJECADIK', // option 255
  ACDEGJKL: 'EGJCADLK', // option 256
  ACDEGIKL: 'EGICADLK', // option 257
  ACDEGIJL: 'EGJCADLI', // option 258
  ACDEGIJK: 'EGJCADIK', // option 259
  ACDEGHKL: 'HGECADLK', // option 260
  ACDEGHJL: 'HGJCADLE', // option 261
  ACDEGHJK: 'HGJCADEK', // option 262
  ACDEGHIL: 'HGECADLI', // option 263
  ACDEGHIK: 'HGECADIK', // option 264
  ACDEGHIJ: 'HGJCADEI', // option 265
  ACDEFJKL: 'CJEDAFLK', // option 266
  ACDEFIKL: 'CEIDAFLK', // option 267
  ACDEFIJL: 'CJEDAFLI', // option 268
  ACDEFIJK: 'CJEDAFIK', // option 269
  ACDEFHKL: 'HEFCADLK', // option 270
  ACDEFHJL: 'HJFCADLE', // option 271
  ACDEFHJK: 'HJECAFDK', // option 272
  ACDEFHIL: 'HEFCADLI', // option 273
  ACDEFHIK: 'HEFCADIK', // option 274
  ACDEFHIJ: 'HJECAFDI', // option 275
  ACDEFGKL: 'CGEDAFLK', // option 276
  ACDEFGJL: 'CGJDAFLE', // option 277
  ACDEFGJK: 'CGJDAFEK', // option 278
  ACDEFGIL: 'CGEDAFLI', // option 279
  ACDEFGIK: 'CGEDAFIK', // option 280
  ACDEFGIJ: 'CGJDAFEI', // option 281
  ACDEFGHL: 'HGFCADLE', // option 282
  ACDEFGHK: 'HGECAFDK', // option 283
  ACDEFGHJ: 'HGJCAFDE', // option 284
  ACDEFGHI: 'HGECAFDI', // option 285
  ABGHIJKL: 'HJBAIGLK', // option 286
  ABFHIJKL: 'HJBAIFLK', // option 287
  ABFGIJKL: 'IJBFAGLK', // option 288
  ABFGHJKL: 'HJBFAGLK', // option 289
  ABFGHIKL: 'HGBAIFLK', // option 290
  ABFGHIJL: 'HJBFAGLI', // option 291
  ABFGHIJK: 'HJBFAGIK', // option 292
  ABEHIJKL: 'EJBAIHLK', // option 293
  ABEGIJKL: 'EJBAIGLK', // option 294
  ABEGHJKL: 'EJBAHGLK', // option 295
  ABEGHIKL: 'EGBAIHLK', // option 296
  ABEGHIJL: 'EJBAHGLI', // option 297
  ABEGHIJK: 'EJBAHGIK', // option 298
  ABEFIJKL: 'EJBAIFLK', // option 299
  ABEFHJKL: 'EJBFAHLK', // option 300
  ABEFHIKL: 'EIBFAHLK', // option 301
  ABEFHIJL: 'EJBFAHLI', // option 302
  ABEFHIJK: 'EJBFAHIK', // option 303
  ABEFGJKL: 'EJBFAGLK', // option 304
  ABEFGIKL: 'EGBAIFLK', // option 305
  ABEFGIJL: 'EJBFAGLI', // option 306
  ABEFGIJK: 'EJBFAGIK', // option 307
  ABEFGHKL: 'EGBFAHLK', // option 308
  ABEFGHJL: 'HJBFAGLE', // option 309
  ABEFGHJK: 'HJBFAGEK', // option 310
  ABEFGHIL: 'EGBFAHLI', // option 311
  ABEFGHIK: 'EGBFAHIK', // option 312
  ABEFGHIJ: 'HJBFAGEI', // option 313
  ABDHIJKL: 'IJBDAHLK', // option 314
  ABDGIJKL: 'IJBDAGLK', // option 315
  ABDGHJKL: 'HJBDAGLK', // option 316
  ABDGHIKL: 'IGBDAHLK', // option 317
  ABDGHIJL: 'HJBDAGLI', // option 318
  ABDGHIJK: 'HJBDAGIK', // option 319
  ABDFIJKL: 'IJBDAFLK', // option 320
  ABDFHJKL: 'HJBDAFLK', // option 321
  ABDFHIKL: 'HIBDAFLK', // option 322
  ABDFHIJL: 'HJBDAFLI', // option 323
  ABDFHIJK: 'HJBDAFIK', // option 324
  ABDFGJKL: 'FJBDAGLK', // option 325
  ABDFGIKL: 'IGBDAFLK', // option 326
  ABDFGIJL: 'FJBDAGLI', // option 327
  ABDFGIJK: 'FJBDAGIK', // option 328
  ABDFGHKL: 'HGBDAFLK', // option 329
  ABDFGHJL: 'HGBDAFLJ', // option 330
  ABDFGHJK: 'HGBDAFJK', // option 331
  ABDFGHIL: 'HGBDAFLI', // option 332
  ABDFGHIK: 'HGBDAFIK', // option 333
  ABDFGHIJ: 'HGBDAFIJ', // option 334
  ABDEIJKL: 'EJBAIDLK', // option 335
  ABDEHJKL: 'EJBDAHLK', // option 336
  ABDEHIKL: 'EIBDAHLK', // option 337
  ABDEHIJL: 'EJBDAHLI', // option 338
  ABDEHIJK: 'EJBDAHIK', // option 339
  ABDEGJKL: 'EJBDAGLK', // option 340
  ABDEGIKL: 'EGBAIDLK', // option 341
  ABDEGIJL: 'EJBDAGLI', // option 342
  ABDEGIJK: 'EJBDAGIK', // option 343
  ABDEGHKL: 'EGBDAHLK', // option 344
  ABDEGHJL: 'HJBDAGLE', // option 345
  ABDEGHJK: 'HJBDAGEK', // option 346
  ABDEGHIL: 'EGBDAHLI', // option 347
  ABDEGHIK: 'EGBDAHIK', // option 348
  ABDEGHIJ: 'HJBDAGEI', // option 349
  ABDEFJKL: 'EJBDAFLK', // option 350
  ABDEFIKL: 'EIBDAFLK', // option 351
  ABDEFIJL: 'EJBDAFLI', // option 352
  ABDEFIJK: 'EJBDAFIK', // option 353
  ABDEFHKL: 'HEBDAFLK', // option 354
  ABDEFHJL: 'HJBDAFLE', // option 355
  ABDEFHJK: 'HJBDAFEK', // option 356
  ABDEFHIL: 'HEBDAFLI', // option 357
  ABDEFHIK: 'HEBDAFIK', // option 358
  ABDEFHIJ: 'HJBDAFEI', // option 359
  ABDEFGKL: 'EGBDAFLK', // option 360
  ABDEFGJL: 'EGBDAFLJ', // option 361
  ABDEFGJK: 'EGBDAFJK', // option 362
  ABDEFGIL: 'EGBDAFLI', // option 363
  ABDEFGIK: 'EGBDAFIK', // option 364
  ABDEFGIJ: 'EGBDAFIJ', // option 365
  ABDEFGHL: 'HGBDAFLE', // option 366
  ABDEFGHK: 'HGBDAFEK', // option 367
  ABDEFGHJ: 'HGBDAFEJ', // option 368
  ABDEFGHI: 'HGBDAFEI', // option 369
  ABCHIJKL: 'IJBCAHLK', // option 370
  ABCGIJKL: 'IJBCAGLK', // option 371
  ABCGHJKL: 'HJBCAGLK', // option 372
  ABCGHIKL: 'IGBCAHLK', // option 373
  ABCGHIJL: 'HJBCAGLI', // option 374
  ABCGHIJK: 'HJBCAGIK', // option 375
  ABCFIJKL: 'IJBCAFLK', // option 376
  ABCFHJKL: 'HJBCAFLK', // option 377
  ABCFHIKL: 'HIBCAFLK', // option 378
  ABCFHIJL: 'HJBCAFLI', // option 379
  ABCFHIJK: 'HJBCAFIK', // option 380
  ABCFGJKL: 'CJBFAGLK', // option 381
  ABCFGIKL: 'IGBCAFLK', // option 382
  ABCFGIJL: 'CJBFAGLI', // option 383
  ABCFGIJK: 'CJBFAGIK', // option 384
  ABCFGHKL: 'HGBCAFLK', // option 385
  ABCFGHJL: 'HGBCAFLJ', // option 386
  ABCFGHJK: 'HGBCAFJK', // option 387
  ABCFGHIL: 'HGBCAFLI', // option 388
  ABCFGHIK: 'HGBCAFIK', // option 389
  ABCFGHIJ: 'HGBCAFIJ', // option 390
  ABCEIJKL: 'EJBAICLK', // option 391
  ABCEHJKL: 'EJBCAHLK', // option 392
  ABCEHIKL: 'EIBCAHLK', // option 393
  ABCEHIJL: 'EJBCAHLI', // option 394
  ABCEHIJK: 'EJBCAHIK', // option 395
  ABCEGJKL: 'EJBCAGLK', // option 396
  ABCEGIKL: 'EGBAICLK', // option 397
  ABCEGIJL: 'EJBCAGLI', // option 398
  ABCEGIJK: 'EJBCAGIK', // option 399
  ABCEGHKL: 'EGBCAHLK', // option 400
  ABCEGHJL: 'HJBCAGLE', // option 401
  ABCEGHJK: 'HJBCAGEK', // option 402
  ABCEGHIL: 'EGBCAHLI', // option 403
  ABCEGHIK: 'EGBCAHIK', // option 404
  ABCEGHIJ: 'HJBCAGEI', // option 405
  ABCEFJKL: 'EJBCAFLK', // option 406
  ABCEFIKL: 'EIBCAFLK', // option 407
  ABCEFIJL: 'EJBCAFLI', // option 408
  ABCEFIJK: 'EJBCAFIK', // option 409
  ABCEFHKL: 'HEBCAFLK', // option 410
  ABCEFHJL: 'HJBCAFLE', // option 411
  ABCEFHJK: 'HJBCAFEK', // option 412
  ABCEFHIL: 'HEBCAFLI', // option 413
  ABCEFHIK: 'HEBCAFIK', // option 414
  ABCEFHIJ: 'HJBCAFEI', // option 415
  ABCEFGKL: 'EGBCAFLK', // option 416
  ABCEFGJL: 'EGBCAFLJ', // option 417
  ABCEFGJK: 'EGBCAFJK', // option 418
  ABCEFGIL: 'EGBCAFLI', // option 419
  ABCEFGIK: 'EGBCAFIK', // option 420
  ABCEFGIJ: 'EGBCAFIJ', // option 421
  ABCEFGHL: 'HGBCAFLE', // option 422
  ABCEFGHK: 'HGBCAFEK', // option 423
  ABCEFGHJ: 'HGBCAFEJ', // option 424
  ABCEFGHI: 'HGBCAFEI', // option 425
  ABCDIJKL: 'IJBCADLK', // option 426
  ABCDHJKL: 'HJBCADLK', // option 427
  ABCDHIKL: 'HIBCADLK', // option 428
  ABCDHIJL: 'HJBCADLI', // option 429
  ABCDHIJK: 'HJBCADIK', // option 430
  ABCDGJKL: 'CJBDAGLK', // option 431
  ABCDGIKL: 'IGBCADLK', // option 432
  ABCDGIJL: 'CJBDAGLI', // option 433
  ABCDGIJK: 'CJBDAGIK', // option 434
  ABCDGHKL: 'HGBCADLK', // option 435
  ABCDGHJL: 'HGBCADLJ', // option 436
  ABCDGHJK: 'HGBCADJK', // option 437
  ABCDGHIL: 'HGBCADLI', // option 438
  ABCDGHIK: 'HGBCADIK', // option 439
  ABCDGHIJ: 'HGBCADIJ', // option 440
  ABCDFJKL: 'CJBDAFLK', // option 441
  ABCDFIKL: 'CIBDAFLK', // option 442
  ABCDFIJL: 'CJBDAFLI', // option 443
  ABCDFIJK: 'CJBDAFIK', // option 444
  ABCDFHKL: 'HFBCADLK', // option 445
  ABCDFHJL: 'CJBDAFLH', // option 446
  ABCDFHJK: 'HJBCAFDK', // option 447
  ABCDFHIL: 'HFBCADLI', // option 448
  ABCDFHIK: 'HFBCADIK', // option 449
  ABCDFHIJ: 'HJBCAFDI', // option 450
  ABCDFGKL: 'CGBDAFLK', // option 451
  ABCDFGJL: 'CGBDAFLJ', // option 452
  ABCDFGJK: 'CGBDAFJK', // option 453
  ABCDFGIL: 'CGBDAFLI', // option 454
  ABCDFGIK: 'CGBDAFIK', // option 455
  ABCDFGIJ: 'CGBDAFIJ', // option 456
  ABCDFGHL: 'CGBDAFLH', // option 457
  ABCDFGHK: 'HGBCAFDK', // option 458
  ABCDFGHJ: 'HGBCAFDJ', // option 459
  ABCDFGHI: 'HGBCAFDI', // option 460
  ABCDEJKL: 'EJBCADLK', // option 461
  ABCDEIKL: 'EIBCADLK', // option 462
  ABCDEIJL: 'EJBCADLI', // option 463
  ABCDEIJK: 'EJBCADIK', // option 464
  ABCDEHKL: 'HEBCADLK', // option 465
  ABCDEHJL: 'HJBCADLE', // option 466
  ABCDEHJK: 'HJBCADEK', // option 467
  ABCDEHIL: 'HEBCADLI', // option 468
  ABCDEHIK: 'HEBCADIK', // option 469
  ABCDEHIJ: 'HJBCADEI', // option 470
  ABCDEGKL: 'EGBCADLK', // option 471
  ABCDEGJL: 'EGBCADLJ', // option 472
  ABCDEGJK: 'EGBCADJK', // option 473
  ABCDEGIL: 'EGBCADLI', // option 474
  ABCDEGIK: 'EGBCADIK', // option 475
  ABCDEGIJ: 'EGBCADIJ', // option 476
  ABCDEGHL: 'HGBCADLE', // option 477
  ABCDEGHK: 'HGBCADEK', // option 478
  ABCDEGHJ: 'HGBCADEJ', // option 479
  ABCDEGHI: 'HGBCADEI', // option 480
  ABCDEFKL: 'CEBDAFLK', // option 481
  ABCDEFJL: 'CJBDAFLE', // option 482
  ABCDEFJK: 'CJBDAFEK', // option 483
  ABCDEFIL: 'CEBDAFLI', // option 484
  ABCDEFIK: 'CEBDAFIK', // option 485
  ABCDEFIJ: 'CJBDAFEI', // option 486
  ABCDEFHL: 'HFBCADLE', // option 487
  ABCDEFHK: 'HEBCAFDK', // option 488
  ABCDEFHJ: 'HJBCAFDE', // option 489
  ABCDEFHI: 'HEBCAFDI', // option 490
  ABCDEFGL: 'CGBDAFLE', // option 491
  ABCDEFGK: 'CGBDAFEK', // option 492
  ABCDEFGJ: 'CGBDAFEJ', // option 493
  ABCDEFGI: 'CGBDAFEI', // option 494
  ABCDEFGH: 'HGBCAFDE', // option 495
} as const;
